// This file was automatically generated from working-with-typed-errors.md by Knit tool. Do not edit.
package arrow.core.examples.test

import kotlin.test.Test
import kotlinx.coroutines.test.runTest
import arrow.website.captureOutput
import kotlinx.knit.test.verifyOutputLines

class TypedErrorsTest {
  @Test fun ExampleTypedErrors03() = runTest {
    arrow.website.examples.exampleTypedErrors03.example()
  }

  @Test fun ExampleTypedErrors05() = runTest {
    arrow.website.examples.exampleTypedErrors05.example()
  }

  @Test fun ExampleTypedErrors06() = runTest {
    arrow.website.examples.exampleTypedErrors06.example()
  }

  @Test fun ExampleTypedErrors07() = runTest {
    arrow.website.examples.exampleTypedErrors07.example()
  }

  @Test fun ExampleTypedErrors11() = runTest {
    arrow.website.examples.exampleTypedErrors11.example()
  }

  @Test fun ExampleTypedErrors12() = runTest {
    arrow.website.examples.exampleTypedErrors12.example()
  }

  @Test fun ExampleTypedErrors15() = runTest {
    arrow.website.examples.exampleTypedErrors15.example()
  }

  @Test fun ExampleTypedErrors16() = runTest {
    arrow.website.examples.exampleTypedErrors16.example()
  }

  @Test fun ExampleTypedErrors18() = runTest {
    arrow.website.examples.exampleTypedErrors18.example()
  }

  @Test fun ExampleTypedErrors19() = runTest {
    arrow.website.examples.exampleTypedErrors19.example()
  }

  @Test fun ExampleTypedErrors20() = runTest {
    arrow.website.examples.exampleTypedErrors20.example()
  }

}
